name: Audio Pipeline

on: [push]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading code from repo
        uses: actions/checkout@v6
      
      - name: Building Docker image
        run: docker build -t audio-processor .